libbpf: set PREFERRED_VERSION to v0.6 to have AF_XDP symbols
Yocto kikrstone is having libbpf v0.7.0 (meta-openembedded) and genavb-tsn is failing with the following error while linking to it:

| /media/work/yocto/yocto-real-time-edge/build-imx-kirkstone/tmp/work/armv8a-poky-linux/genavb-tsn/5.0+gitAUTOINC+d9eec1e
  83c-r0/git/linux/net_xdp.c: In function 'net_xdp_umem_create':

| /media/work/yocto/yocto-real-time-edge/build-imx-kirkstone/tmp/work/armv8a-poky-linux/genavb-tsn/5.0+gitAUTOINC+d9eec1e
  83c-r0/git/linux/net_xdp.c:299:9: error: 'xsk_umem__create' is deprecated: libbpf v0.7+: AF_XDP support deprecated and moved to libxdp [-Werror=deprecated-declarations]

|   299 |         rc = xsk_umem__create(&umem->umem, umem_buffer_pool_area, BUF_POOL_SIZE, &umem->fill_ring, &umem->completion_ring, &cfg);

|       |         ^~

AF_XDP API has been deprecated in v0.7.0 and moved to a separate libxdp.
Since there is no yocto recipe to build libxdp (xdp-tools) yet, set the preferred version for real time edge distro
to be the latest version (v0.6.1) with AF_XDP API symbols

Signed-off-by: Marouen Ghodhbane <marouen.ghodhbane@nxp.com>