genavb-tsn: rework kernel module recipes
The current recipe is not takiung full advantage of the module class
as the GenAVB/TSN linux module is split in two phases/Makefile: One parent Makefile
called to generate the modules sources in a custom objects directory which calls the kernel
module Makefile afterwards. Calling directly the parent Makefile from the recipe prevents
passing all environment variables set in module.bbclass (MODLIB, CC, ...) to the modules Makefile
unless explicetly exported, which is not the case. The current model is causing few QA issues/warnings:

The following error is coming from the new enabled usrmerge feature (imposed by systemd) and forcing to
get rid of /bin /lib ... directories and user their counterpart in /usr/.

ERROR: kernel-module-genavb-tsn-6_1+git-r0 do_package: QA Issue: kernel-module-genavb-tsn: Files/directories were installed but not shipped in any package:
  /lib/modules/6.6.3-rt16-g5d26af297ceb/genavb/genavbtsn_net_avb.ko
  /lib/modules/6.6.3-rt16-g5d26af297ceb/genavb/genavbtsn_ipc.ko
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
kernel-module-genavb-tsn: 2 installed and not shipped files. [installed-vs-shipped]
ERROR: kernel-module-genavb-tsn-6_1+git-r0 do_package: Fatal QA errors were found, failing task.

The following warning caused by missing the -fdebug-prefix-map set in ${KERNEL_CC} and used in module.bbclass:

WARNING: kernel-module-genavb-tsn-6_1+git-r0 do_package_qa: QA Issue:
File /usr/lib/modules/6.6.3-rt16-g5d26af297ceb/genavb/.debug/genavbtsn_net_avb.ko in package kernel-module-genavb-tsn-dbg contains ref
erence to TMPDIR
File /usr/lib/modules/6.6.3-rt16-g5d26af297ceb/genavb/.debug/genavbtsn_ipc.ko in package kernel-module-genavb-tsn-dbg contains reference to TMPDIR [buildpaths]

The new implementation is using the do_configure() task to generate the modules sources directory
under the build directory ${B} and then invoking the module Makefile directly using the oe_runmake
extra options.

Signed-off-by: Marouen Ghodhbane <marouen.ghodhbane@nxp.com>